export const TableData =[
  {
      "name": "Najam",
      "code": "ER-najam",
      "assigned": "laptop",
      "date": "06-03-2023",
  },
  {
      "name": "Ahmed",
      "code": "ER-ARM",
      "assigned": "laptop",
      "date": "02-02-2023",
  },
  {
      "name": "Raza",
      "code": "ER-Raza",
      "assigned": "laptop",
      "date": "04-02-2023",
  },
  {
      "name": "Uzair",
      "code": "ER-uzair",
      "assigned": "laptop",
      "date": "05-02-2023",
  },
  {
      "name": "Sami",
      "code": "ER-sami",
      "assigned": "laptop",
      "date": "07-02-2023",
  },
  {
      "name": "Ali",
      "code": "ER-ali",
      "assigned": "keyboard",
      "date": "08-02-2023",
  },
  {
      "name": "Talha",
      "code": "ER-talha",
      "assigned": "keyboard",
      "date": "07-02-2023",
  },
  {
      "name": "Fahad",
      "code": "ER-fahad",
      "assigned": "keyboard",
      "date": "10-02-2023",
  },
  {
      "name": "Saad",
      "code": "ER-saad",
      "assigned": "keyboard",
      "date": "12-02-2023",
  },
  {
      "name": "Hassan",
      "code": "ER-hassan",
      "assigned": "laptop",
      "date": "15-02-2023",
  },
  {
      "name": "Zain",
      "code": "ER-zain",
      "assigned": "mobile",
      "date": "17-02-2023",
  },
  {
      "name": "Owais",
      "code": "ER-owais",
      "assigned": "mobile",
      "date": "20-02-2023",
  },
  {
      "name": "Hamza",
      "code": "ER-hamza",
      "assigned": "mobile",
      "date": "22-02-2023",
  },
  {
      "name": "Bilal",
      "code": "ER-bilal",
      "assigned": "mobile",
      "date": "25-02-2023",
  },
  {
      "name": "Junaid",
      "code": "ER-junaid",
      "assigned": "laptop",
      "date": "28-02-2023",
  },
  {
    "name": "Ali",
    "code": "ER-Ali",
    "assigned": "macbooks",
    "date": "09-03-2023",
  },
  {
    "name": "Hassan",
    "code": "ER-Hassan",
    "assigned": "macbooks",
    "date": "10-03-2023",
  },
  {
    "name": "Ahsan",
    "code": "ER-Ahsan",
    "assigned": "macbooks",
    "date": "11-03-2023",
  },
  {
    "name": "Usman",
    "code": "ER-Usman",
    "assigned": "macbooks",
    "date": "12-03-2023",
  },
  {
    "name": "Bilal",
    "code": "ER-Bilal",
    "assigned": "macbooks",
    "date": "13-03-2023",
  },
  {
    "name": "Saad",
    "code": "ER-Saad",
    "assigned": "laptop",
    "date": "14-03-2023",
  },
  {
    "name": "Hamza",
    "code": "ER-Hamza",
    "assigned": "laptop",
    "date": "15-03-2023",
  },
  {
    "name": "Shoaib",
    "code": "ER-Shoaib",
    "assigned": "laptop",
    "date": "16-03-2023",
  },
  {
    "name": "Faisal",
    "code": "ER-Faisal",
    "assigned": "laptop",
    "date": "17-03-2023",
  },
  {
    "name": "Talha",
    "code": "ER-Talha",
    "assigned": "laptop",
    "date": "18-03-2023",
  },
  {
    "name": "Noman",
    "code": "ER-Noman",
    "assigned": "laptop",
    "date": "19-03-2023",
  },
  {
    "name": "Junaid",
    "code": "ER-Junaid",
    "assigned": "laptop",
    "date": "20-03-2023",
  },
  {
    "name": "Asad",
    "code": "ER-Asad",
    "assigned": "mouse",
    "date": "21-03-2023",
  },
  {
    "name": "Imran",
    "code": "ER-Imran",
    "assigned": "mouse",
    "date": "22-03-2023",
  },
  {
    "name": "Yasin",
    "code": "ER-Yasin",
    "assigned": "mouse",
    "date": "23-03-2023",
  },
  {
    "name": "Zaid",
    "code": "ER-Zaid",
    "assigned": "mouse",
    "date": "24-03-2023",
  },
  {
    "name": "Arslan",
    "code": "ER-Arslan",
    "assigned": "laptop",
    "date": "25-03-2023",
  },
  {
    "name": "Fahad",
    "code": "ER-Fahad",
    "assigned": "laptop",
    "date": "26-03-2023",
  },
  {
    "name": "Sufyan",
    "code": "ER-Sufyan",
    "assigned": "laptop",
    "date": "27-03-2023",
  },

  {
    "name": "Sufyan",
    "code": "ER-Sufyan",
    "assigned": "laptop",
    "date": "06-03-2023",
  },
];

